import { createApp } from "vue";
import ManagePage from "./manageUi.vue";
import "@/assets/main.css";
import { addIcons, OhVueIcon } from "oh-vue-icons";
import { BiPlusCircleDotted, BiTrash, FaSort } from "oh-vue-icons/icons";
import PrimeVue from "primevue/config";
addIcons(FaSort);
addIcons(BiTrash);
addIcons(BiPlusCircleDotted);
const optionPage = createApp(ManagePage);
optionPage.use(PrimeVue);
optionPage.component("v-icon", OhVueIcon);
optionPage.mount("#manage-page");
